default_roles:
  - amdgpu_top
  - baobab
  - bash
  - bpytop
  - brave
  - brscan4
  - calibre
  - chromium
  - dbeaver
  - emacs
  - fastfetch
  - firefox
  - freecad
  - gimp
  - git
  - gnome-browser-connector
  - gnome-calendar
  - gnome-characters
  - gnome-connections
  - gnome-font-viewer
  - gnome-logs
  - gnome-shell-extensions
  - gnome-software
  - gstm
  - inkscape
  - keepassxc
  - kicad
  - ledger-live
  - libreoffice-still
  - mc
  - megasync
  - neofetch
  - obs-studio
  - openscad
  - pamac
  - podman
  - printer
  - prusa-slicer
  - pyenv
  - rclone
  - remmina
  - signal-desktop
  - simple-scan
  - snapshot
  - starship
  - syncthing
  - telegram-desktop
  - tmuxp
  - transmission-gtk
  - uv
  - virt-manager
  - vlc
  - zsh

desktops:
  - gnome
  #- plasma

user_shell: zsh

amdgpu_top: yes

brscan4:
  ip: "192.168.1.199"
  model: "DCP-J552DW"
  name: Brother

git:
  user_name: "Juan Carlos Coruña"
  user_email: oggers@gmail.com

keepassxc:
  pass:
    key_files:
      - name: .keepass.oggers
        vault_path: "personal/keepassxc/key_file_oggers"
      - name: .keepass.clara
        vault_path: "personal/keepassxc/key_file_clara"
      - name: .keepass.bizak
        vault_path: "personal/keepassxc/key_file_bizak"

printer:
  name: "Brother_DCP-J552DW"
  ipv4_address: "192.168.1.199"

remmina:
  connections:
    - name: adminbizak@proteo
      group: "Servidores Windows"
      server: "newproteo.local.zabik"
      protocol: RDP
      username: bizaksgacom
      domain: DOMGSMNT
    - name: admin@ariel
      group: "Servidores Windows"
      server: ariel.local.zabik
      protocol: RDP
      username: admin
      domain: local.zabik
    - name: admin@caronte.local.zabik
      group: "Servidores Windows"
      server: caronte.loca.zabik
      protocol: RDP
      username: admin
      domain: DOMGSMNT
    - name: admin@europa (srvnavision)
      group: "Servidores Windows"
      server: srvnavision.local.zabik
      protocol: RDP
      username: admin
      domain: DOMGSMNT
    - name: admin@herse (Com. SGA)
      group: "Servidores Windows"
      server: herse.local.zabik
      protocol: RDP
      username: admin
      domain: DOMGSMNT
    - name: admin@herse
      group: "Servidores Windows"
      server: herse.local.zabik
      protocol: RDP
      username: admin
      domain: DOMGSMNT
    - name: admin@kore
      group: "Servidores Windows"
      server: kore.local.zabik
      protocol: RDP
      username: admin
      domain: DOMGSMNT
    - name: bizak@newproteo (Aliernet)
      group: "Servidores Windows"
      server: newproteo.local.zabik
      protocol: RDP
      username: bizak
      domain: DOMGSMNT
    - name: bizak@pc-inacatalogo
      group: "Servidores Windows"
      server: pc-inacatalogo.local.zabik
      protocol: RDP
      username: bizak
      domain: DOMGSMNT
    - name: bizaksgacom@newproteo SGA
      group: "Servidores Windows"
      server: newproteo.local.zabik
      protocol: RDP
      username: bizaksgacom
      domain: DOMGSMNT
    - name: comun@proteo (srvrdp)
      group: "Servidores Windows"
      server: proteo.local.zabik
      protocol: RDP
      username: comun
      domain: DOMGSMNT
    - name: jcn@europa (srvnavision)
      group: "Servidores Windows"
      server: srvnavision.local.zabik
      protocol: RDP
      username: jcn
      domain: DOMGSMNT
    - name: jcn@hyperion
      group: "Servidores Windows"
      server: hyperion.local.zabik
      protocol: RDP
      username: jcn
      domain: DOMGSMNT
    - name: jcn@prometeo (NAV)
      group: "Servidores Windows"
      server: prometeo.local.zabik
      protocol: RDP
      username: jcn
      domain: DOMGSMNT
    - name: jcn@proteo (conexiones almacén)
      group: "Servidores Windows"
      server: proteo.local.zabik
      protocol: RDP
      username: admin
      domain: DOMGSMNT
    - name: jcn@srverptest
      group: "Servidores Windows"
      server: srverptest.local.zabik
      protocol: RDP
      username: jcn
      domain: DOMGSMNT
    - name: sgacom@proteo (Versa Aliernet)
      group: "Servidores Windows"
      server: proteo.local.zabik
      protocol: RDP
      username: sgacom
      domain: DOMGSMNT

    - name: triton InaCatalog
      group: "Servidores Windows"
      server: triton.local.zabik
      protocol: RDP
      username: inaseadmin
      domain: DOMGSMNT


ssh:
  pass:
    ssh_keys:
      - name: id_rsa
        vault_path: "personal/ssh/id_rsa"
      - name: id_ed25519
        vault_path: "personal/ssh/id_ed25519"
    authorized_keys:
      - name: id_ed25519
        vault_path: "personal/ssh/id_ed25519"
  config:
    hosts:
      - name: apym4
        hostname: apym4.apanymantel.com
        port: 22222
      - name: apym5
        hostname: apym5.apanymantel.com
        port: 22222
      - name: hockenheim.oggers.com.es
        hostname: hockenheim.oggers.com.es
        port: 22222
      - name: bitbucket.org
        HostkeyAlgorithms: +ssh-rsa
        PubkeyAcceptedAlgorithms: +ssh-rsa
