---
packages:
  - arandr
  - autorandr
  - brightnessctl
  - flameshot
  - khal
  # - nerd-fonts  # optional dependency for rofimoji
  # - otf-font-awesome  # optional dependency for rofimoji
  - python-iwlib  # needed for wlan widget
  - python-psutil  # needed for memory widget
  - qalculate-gtk
  - rofi
  - rofimoji
  - qtile
  # 'tt-font-awesome  # optional dependency for rofimoji'
  # - ttf-nerd-fonts-symbols
  - xclip

aur_packages:
  - python-pulsectl-asyncio
  - qtile-extras
