---
packages:
- arduino
- arduino-avr-core
- chromium
- curl
- docker
- firefox-i18n-es-es
- keepassx
- keepassxc
- kicad
- kicad-library
- kicad-library-3d
- mc
#- nodejs
- npm
- obs-studio
- openscad
- prusa-slicer
- pyenv
- pyenv-virtualenv
- python2-virtualenv
- rsnapshot
- simple-scan
- tigervnc
- virtualbox
- wget
- xorg-setxkbmap
- yarn
- yay
- youtube-dl
aur_packages:
- dropbox
- freecad
- modelio-bin
