---
packages:
  - calibre
  - chromium
  - curl
  - fakeroot
  - firefox-i18n-es-es
  - freecad
  - freerdp
  - guvcview
  - keepassxc
  - kicad
  - kicad-library
  - kicad-library-3d
  - libvncserver
  - mc
  - nodejs-lts-fermium
  #- npm
  - obs-studio
  - openscad
  - prusa-slicer
#  - python2-virtualenv
  - remmina
  - rsnapshot
  - simple-scan
  - tigervnc
  - virtualbox
  - wget
#  - xorg-setxkbmap
  - yarn
  - yay
  - youtube-dl
aur_packages:
  - gstm
  - megasync
  - pyenv-virtualenv
#  - dropbox
#  - modelio-bin
