---
# file: roles/shell/tasks/main.yml
- name: Shell | Set linux distribution specific variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Shell | Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ packages }}"

- ansible.builtin.include_task: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
