---
# file: roles/shell/tasks/starship.yml
# https://github.com/andrewrothstein/ansible-starship/blob/main/defaults/main.yml
- name: Shell | Look for install in {{ starship_install_dir }}
  ansible.builtin.stat:
    path: "{{ starship_install_dir }}"
  become: yes
  changed_when: false
  register: starship_binary

- name: Shell | Downloading and installing starship
  when: not starship_binary.stat.exists
  block:
    - name: Downloading
