- name: Collecting Facts
  hosts: local
  #vars_files: "encrypted.yml"
  pre_tasks:
    - name: Load bizak-destop variables
      include_vars: vars/bizak-desktop.yml
      tags: bizak-desktop

    - name: Load bizak-laptop variables
      include_vars: vars/bizak-laptop.yml
      tags: bizak-laptop

    - name: Load home variables
      include_vars: vars/home.yml
      tags: home

    - name: Copy .vault_pass.txt
      copy: src="files/.vault_pass.txt" dest="{{ ansible_user_dir }}"


  tasks:
    - name: Set ssh config
      template:
        src: templates/ssh_config.j2
        dest: "{{ ansible_user_dir }}/.ssh/config"
      tags: always

  roles:
    - role: git
      tags: home, bizak-desktop, bizak-laptop
    - role: packages
      tags: packages, home, bizak-desktop, bizak-laptop
#    - role: bin
#      tags: home, bizak-desktop, bizak-laptop
    - role: docker
      tags: home, bizak-desktop, bizak-laptop
    - role: syncthing
      tags: home, bizak-desktop, bizak-laptop
    - role: doomemacs
      tags: emacs, home, bizak-desktop, bizak-laptop
#    - role: syncthing
#      tags: home, bizak-desktop, bizak-laptop

