---
# file: roles/packages/tasks/main.yml

- name: Set specific variables
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
  - "{{ ansible_distribution }}.yml"
  - "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ packages }}"
  become: true

- name: Install aur packages
  aur:
    name: "{{ item }}"
    skip_installed: true
  with_items:
  - "{{ aur_packages }}"

- name: Configure setxkbmap
  copy:
    src: "files/swap_ctrl_caps.desktop"
    dest: "~/config/autostart/"
