---
# file: i3/vars/ManjaroLinux.yml
i3_packages_distrib:
  - artwork-i3
  - manjaro-i3-settings
  #- lxappearance
  #- lxinput
  - terminus-font
  - ttf-inconsolata
  - xterm
  - xdg-user-dirs
  - bmenu
  - manjaro-hello
  - xfce4-power-manager
  - kvantum-manjaro
