---
packages:
  - emacs-wayland
  - ripgrep
  - fd
  - shellcheck
  - make  # needed to compile vterm-module
  - cmake  # needed to compile vterm-module
  - python-lsp-server
  - python-pylint
  - flake8
  - texlive-bin
  - texlive-core
  - texlive-science
  - keychain
  - haskell-language-server  # haskell
  - hoogle  # haskell
