---
# file: keepassxc/tasks/key_files.yml
  - name: "{{ role_name }} | Deploy [{{ item.name }}] key file"
    ansible.builtin.copy:
      dest: "{{ ansible_user_dir }}/{{ item.name }}"
      content: |
        {{ lookup('pipe', 'pass show ' + item.vault_path) }}
      mode: "0600"
    #no_log: true
