---
# file: mc/tasks/Archlinux.yml
- name: "{{ role_name }} | Install"
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - mc
    - aspell-en  # to avoid error message when opening a file

- name: "{{ role_name }} | Ensure mc directory structure exists"
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "0755"
    state: directory
  loop:
    - ~/.config
    - ~/.config/mc
