---
# file: zsh/tasks/main.yml
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Copy .zcompdump"
  ansible.builtin.copy:
    src: ".zcompdump"
    dest: "{{ ansible_user_dir }}/.zcompdump"
    mode: "0644"

- name: "{{ role_name }} | Set zsh shell for user {{ ansible_user_id }}"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  when: "{{ user_shell == 'zsh' }}"
  become: yes
