---
# file: printer/tasks/main.yml
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Include the user in group lp"
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: lp
    append: yes
  become: true

# lpadmin
# -p destination  Specify/add named destination. This can be arbitrary e.g. foobar.
# -E              Enable and accept jobs on the printer (after -p)
# -v device-uri   Specify the device URI for the printer.
# -m model        Specify a standard model/PPD file for the printer. Must be 'everywhere'.
# See: https://wiki.gentoo.org/wiki/Driverless_printing
- name: "{{ role_name }} | Add printer"
  ansible.builtin.shell: |
    lpadmin -p "{{ printer.name }}" -E -v "ipp://{{ printer.ipv4_address }}/ipp" -m everywhere
  register: printer_lpadmin
  changed_when: printer_lpadmin.rc != 0
  become: true

- name: "{{ role_name }} | Enable the printer"
  ansible.builtin.shell: |
    cupsenable "{{ printer.name }}"
  register: printer_cupsenable
  changed_when: printer_cupsenable.rc != 0
  become: true
