---
# file: i3/tasks/main.yml
# testing ssh-agent
# ~/.bash_profile
# ~/.xinitrc

- name: Install antergos i3
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ i3_packages }}"

- name: i3 config directories
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  with_items:
    - ".config/i3"
    - ".config/i3status"
    - ".config/ranger"
    - ".config/dunst"

- name: Copy files
  copy:
    src: files/.profile
    dest: "{{ ansible_user_dir }}/.profile"
    mode: 0644

# - name: Copy files
#   copy:
#     src: files/start-gnome-keyring.sh
#     dest: "{{ ansible_user_dir }}/.config/i3/start-gnome-keyring.sh"
#     mode: 0755

- name: Configure i3
  template:
    src: templates/config.j2
    dest: "{{ ansible_user_dir }}/.config/i3/config"
  notify: Restart i3

- name: Configure i3status
  template:
    src: templates/i3status.conf.j2
    dest: "{{ ansible_user_dir }}/.config/i3status/config"
  notify: Restart i3

- name: Configure dunst
  template:
    src: templates/dunstrc.j2
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"

- name: Config files
  copy:
    src: "files/{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/{{ item }}"
  with_items:
    - "ranger/rc.conf"

- name: Config ssh
  template:
    src: templates/ssh_config.j2
    dest: "{{ ansible_user_dir }}/.ssh/config"
