---
# file: brscan4/tasks/main.yml
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | Check brsaneconfig4 has been executed"
  ansible.builtin.command: "awk '/^DEVIE={{ brscan4.name }}.*/{count++} END{print count+0}' /opt/brother/scanner/brscan4/brsanenetdevice4.cfg"
  register: brsanenetdevice4
  changed_when: false

- name: "{{ role_name }} | Execute brsaneconfig4 -a name='{{ brscan4.name }}' model='{{ brscan4.model }}' ip={{ brscan4.ip }}"
  ansible.builtin.command: "brsaneconfig4 -a name='{{ brscan4.name }}' model='{{ brscan4.model }}' ip={{ brscan4.ip }}"
  when: brsanenetdevice4.stdout == '0'
  become: yes
  notify: Restart saned
