---
# file: emacs/tasks/Archlinux.yml
- name: "{{ role_name }} | Check if session type is x11 or wayland"
  ansible.builtin.command: echo $XDG_SESSION_TYPE
  register: session_type
  changed_when: false

- name: "{{ role_name }} | Install emacs x11"
  ansible.builtin.pacman:
    name: emacs
    state: present
  become: yes
  when: "'x11' in session_type.stdout.lower()"

- name: "{{ role_name }} | Install emacs wayland"
  ansible.builtin.pacman:
    name: emacs-wayland
    state: present
  become: yes
  when: "'wayland' in session_type.stdout.lower()"

- name: "{{ role_name }} | Install emacs package and dependencies"
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - ripgrep
    - fd
    - shellcheck
    - make  # needed to compile vterm-module
    - cmake  # needed to compile vterm-module
    - python-lsp-server
    - python-pylint
    - flake8
    - texlive-bin
    - texlive-core
    - texlive-science
    - keychain
    #- haskell-language-server  # haskell
    #- hoogle  # haskell
