---
# file: roles/emacs/tasks/main.yml

- name: Install emacs
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - emacs
    - powerline-fonts

- name: Install packages
  command: yaourt -S ttf-symbola --noconfirm 
 
- name: spacemacs already installed?
  stat: path="{{ ansible_user_dir }}/.emacs.d/spacemacs.mk"
  register: spacemacs
  tags: bootstrap

- name: Clone Spacemacs repository
  git: repo="{{ spacemacs_repository }}" version="{{ spacemacs_branch }}" dest="{{ ansible_user_dir }}/.emacs.d" depth=1
  when: spacemacs.stat.exists == False
  tags: bootstrap

- name: Copy .spacemacs
  template: src="spacemacs.j2" dest="{{ ansible_user_dir }}/.spacemacs"

- name: Copy .emacs.d/private
  copy: src="files/emacs.d/private" dest="{{ ansible_user_dir }}/.emacs.d/"

- name: Copy .vault_pass.txt
  copy: src="files/.vault_pass.txt" dest="{{ ansible_user_dir }}"

- name: Install desktop file
  template: src="emacsclient.desktop.j2" dest="{{ lookup('env', 'HOME') }}/.local/share/applications/emacsclient.desktop"
  register: result

- name: Refresh cache database of mime types handled by desktop files
  command: update-desktop-database "{{ lookup('env', 'HOME') }}/.local/share/applications"
  when: result.changed

- name: Update EDITOR
  lineinfile:
    path: /etc/environment
    regexp: '^EDITOR='
    line: 'EDITOR=emacsclient'
  become: yes
