---
# file: roles/emacs/tasks/main.yml

- name: Install emacs
  package:
    name: "{{ item }}"
    state: latest
  become: yes
  with_items:
    - emacs
    - powerline-fonts
    # - adobe-source-code-pro-fonts

- name: Install ttf-symbola
  aur:
    name: "{{ item }}"
    skip_installed: yes
  with_items:
    - ttf-symbola
    # - emacs-all-the-icons
    - nodejs-tern

#- name: Check ttf-symbola package
#  command: pacman -Qi ttf-symbola
#  register: pacman_check
#  changed_when: false

#- debug:
#    msg: "{{ pacman_check }}"

#- name: Install packages
#  command: pamac build ttf-symbola 
#  command: yaourt -S ttf-symbola --noconfirm 
#  when: pacman_check.get('rc', 0) == 1

- name: spacemacs already installed?
  stat: path="{{ ansible_user_dir }}/.emacs.d/spacemacs.mk"
  register: spacemacs
  tags: bootstrap

- name: Clone Spacemacs repository
  git: repo="{{ spacemacs_repository }}" version="{{ spacemacs_branch }}" dest="{{ ansible_user_dir }}/.emacs.d" depth=1
  when: spacemacs.stat.exists == False
  tags: bootstrap

- name: Clone .spacemacs.d
  git:
    repo: git@gitlab.com:oggers/spacemacs.d.git
    dest: "{{ ansible_user_dir }}/.spacemacs.d"

- name: Copy .emacs.d/private
  copy: src="files/emacs.d/private" dest="{{ ansible_user_dir }}/.emacs.d/"

- name: Copy .vault_pass.txt
  copy: src="files/.vault_pass.txt" dest="{{ ansible_user_dir }}"

- name: Check desktop directory
  stat:
    path: "{{ lookup('env', 'HOME') }}/.local/share/applications/"
  register: desktop_dir

- name: Install desktop file
  template: src="emacsclient.desktop.j2" dest="{{ lookup('env', 'HOME') }}/.local/share/applications/emacsclient.desktop"
  register: result
  when: desktop_dir.stat.exists == true

- name: Install org-protocol desktop file
  template: src="org-protocol.desktop.j2" dest="{{ lookup('env', 'HOME') }}/.local/share/applications/org-protocol.desktop"
  register: result_org_protocol
  when: desktop_dir.stat.exists == true

- name: Refresh cache database of mime types handled by desktop files
  command: update-desktop-database "{{ lookup('env', 'HOME') }}/.local/share/applications"
  when: desktop_dir.stat.exists and (result.changed or result_org_protocol.changed)

- name: Update EDITOR
  lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    regexp: '^EDITOR='
    line: 'EDITOR="emacsclient -c"'

- name: Enable systemd
  service:
    enabled: yes
    name: emacs.service
    scope: user
    # user: yes

