---
# file: uv/tasks/main.yml
- name: "{{ role_name }} | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ ansible_distribution }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ ansible_distribution }}"
  ansible.builtin.include_tasks: "{{ ansible_distribution }}.yml"
  when: distribution_config.stat.exists

- name: "{{ role_name }} | uv already installed?"
  ansible.builtin.stat:
    path: "{{ ansible_user_dir }}/.local/bin/uv"
  register: uv_installed
  changed_when: false

- name: "{{ role_name }} | Install uv"
  ansible.builtin.shell: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
  when: not uv_installed.stat.exists

- name: "{{ role_name }} | Enable zsh autocompletion"
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    prepend_newline: yes
    append_newline: yes
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK role uv"
    block: |
      eval "$(uv --generate-shell-completion zsh)"
      eval "$(uvx --generate-shell-completion zsh)"

- name: "{{ role_name }} | Enable bash autocompletion"
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    prepend_newline: yes
    append_newline: yes
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK role uv"
    block: |
      eval "$(uv --generate-shell-completion bash)"
      eval "$(uvx --generate-shell-completion bash)"
