---
# file: i3/defaults/main.yml

i3_packages:
  - arandr
  # - dmenu
  - galculator
  - gpicview
  - gvfs-google
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-smb
  # - i3-wm
  # - i3status
  - moc
  - network-manager-applet
  - networkmanager-openvpn
  - networkmanager-pptp
  # - notify-osd
  - pcmanfm
  - polkit-gnome
  - python-pysmbc
  # - scrot
  - termite
  - udiskie
  - volumeicon
  - xfburn
  # - i3-gaps
  - numlockx
  # - ttf-font-awesome
  - w3m
  - ranger
  - flameshot
  - clipit
