---
# file: i3/defaults/main.yml

i3_packages:
  - arandr
  - awesome-terminal-fonts
  # - dmenu
  - file-roller
  - galculator
  - gpicview
  - gvfs-google
  - gvfs-gphoto2
  - gvfs-mtp
  - gvfs-smb
  # - i3-wm
  - i3lock
  # - i3status
  - kalu
  - lxappearance-gtk3
  - lxinput-gtk3
  - moc
  - mpv
  - network-manager-applet
  - networkmanager-openvpn
  - networkmanager-pptp
  - nitrogen
  - notify-osd
  - pcmanfm
  - polkit-gnome
  - python-pysmbc
  # - scrot
  - termite
  - udiskie
  - volumeicon
  - xdg-user-dirs-gtk
  - xfburn
  - xscreensaver
  - i3-gaps
  - py3status
  - rofi
  - compton
  # - ttf-font-awesome
  - w3m
  - ranger
  - flameshot
