---
# file: gnome-software/tasks/Archlinux.yml
- name: "{{ role_name }} | Install gnome-software with flatpak"
  ansible.builtin.pacman:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - gnome-software
    - flatpak
