---
# file: openbox/tasks/main.yml

- name: Install packages for openbox
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ openbox_packages }}"

- name: Setup autostart
  lineinfile:
    path: ~/.config/openbox/autostart
    line: "{{ item  }}"
  with_items: "{{ openbox_autostart }}"
